apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
  labels:
    app: httpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
#      imagePullSecrets:
#      - name: cloudnative
      containers:
      - name: httpserver
        image: yexy0123/go-server:1.0.0
        ports:
        - containerPort: 8888
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8888
            scheme: HTTP
          failureThreshold: 5
          periodSeconds: 3
        startupProbe:
          httpGet:
            path: /healthz
            port: 8888
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8888
            httpHeaders:
            - name: Custom-Header
              value: Awesome
          failureThreshold: 3
          periodSeconds: 3